#!/bin/bash

# Script to add all Moodle submodules

declare -A submodules=(
  ["mod/checklist"]="https://github.com/davosmith/moodle-checklist.git"
  ["mod/checkmark"]="https://github.com/academic-moodle-cooperation/moodle-mod_checkmark.git"
  ["mod/diary"]="https://github.com/drachels/moodle-mod_diary.git"
  ["mod/journal"]="https://github.com/elearningsoftware/moodle-mod_journal.git"
  ["mod/mootimeter"]="https://github.com/mebis-lp/moodle-mod_mootimeter.git"
  ["mod/organizer"]="https://github.com/academic-moodle-cooperation/moodle-mod_organizer.git"
  ["mod/oublog"]="https://github.com/moodleou/moodle-mod_oublog.git"
  ["mod/panopto"]="https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto.git"
  ["mod/panoptosubmission"]="https://github.com/Panopto/moodle-mod_panoptosubmission.git"
  ["mod/questionnaire"]="https://github.com/PoetOS/moodle-mod_questionnaire.git"
  ["mod/scheduler"]="https://github.com/bostelm/moodle-mod_scheduler.git"
  ["mod/publication"]="https://github.com/academic-moodle-cooperation/moodle-mod_publication.git"
  ["mod/subcourse"]="https://github.com/catalyst/moodle-mod_subcourse.git"
  ["mod/vpl"]="https://github.com/CentreCyberKnight/moodle-mod_vplAnte.git"
  ["mod/book/tool/wordimport"]="https://github.com/ecampbell/moodle-booktool_wordimport.git"
  ["mod/assign/feedback/cloudpoodll"]="https://github.com/justinhunt/moodle-assignfeedback_cloudpoodll.git"
  ["mod/assign/submission/cloudpoodll"]="https://github.com/justinhunt/moodle-assignsubmission_cloudpoodll.git"
  ["mod/data/field/poodll"]="https://github.com/justinhunt/moodle-mod_data_field_poodll.git"
  ["question/type/cloudpoodll"]="https://github.com/justinhunt/moodle-qtype_cloudpoodll.git"
  ["question/type/multichoiceset"]="https://github.com/ecampbell/moodle-qtype_multichoiceset.git"
  ["question/type/stack"]="https://github.com/maths/moodle-qtype_stack.git"
  ["question/type/vplquestion"]="https://gricad-gitlab.univ-grenoble-alpes.fr/moodle-moodle-qtype_vplquestion.git"
  ["question/type/dfcbmexplicitvalidate"]="https://github.com/maths/moodle-qbehaviour_dfcbmexplicitvaildate.git"
  ["question/type/dfexplicitvalidate"]="https://github.com/maths/moodle-qbehaviour_dfexplicitvaildate.git"
  ["question/type/deferredallnothing"]="https://github.com/dthies/moodle-qbehaviour_deferredallnothing.git"
  ["question/type/adaptiveallnothing"]="https://github.com/dthies/moodle-qbehaviour_adaptiveallnothing.git"
  ["question/format/wordtable"]="https://github.com/ecampbell/moodle-qformat_wordtable.git"
  ["mod/quiz/report/essaydownload"]="https://github.com/PhilippImhof/moodle-quiz_essaydownload.git"
  ["blocks/xp"]="https://github.com/FMCorz/moodle-block_xp.git"
  ["blocks/checklist"]="https://github.com/davosmith/moodle-block_checklist.git"
  ["blocks/cinfo"]="https://github.com/sokunthearithmakara/block_cinfo.git"
  ["blocks/microsoft"]="https://github.com/microsoft/moodle-block_microsoft.git"
  ["blocks/panopto"]="https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto.git"
  ["blocks/sharing_cart"]="https://github.com/donhinkelman/moodle-block_sharing_cart.git"
  ["blocks/rbreport"]="https://github.com/moodleworkplace/moodle-block_rbreport.git"
  ["mod/attendance"]="https://github.com/danmarsden/moodle-mod_attendance.git"
  ["lib/editor/tiny/plugins/wordimport"]="https://codeberg.org/linos/moodle-tiny_wordimport.git"
  ["lib/editor/tiny/plugins/cloze"]="https://github.com/srobotta/moodle-tiny_cloze.git"
  ["lib/editor/tiny/plugins/fontcolor"]="https://github.com/bfh/moodle-tiny_fontcolor.git"
  ["lib/editor/tiny/plugins/poodll"]="https://github.com/justinhunt/moodle-tiny_poodll.git"
  ["lib/editor/tiny/plugins/wordlimit"]="https://codeberg.org/linos/moodle-tiny_wordlimit.git"
  ["lib/editor/tiny/plugins/panoptoltibutton"]="https://github.com/Panopto/moodle-tiny_panoptoltibutton.git"
  ["filter/poodll"]="https://github.com/justinhunt/moodle-filter_poodll.git"
  ["plagiarism/turnitinsim"]="https://github.com/turnitin/moodle-plagiarism_turnitinsim.git"
  ["grade/report/rubrics"]="https://github.com/brickfield/moodle-gradereport_rubrics.git"
  ["grade/report/gradeconfigwizard"]="https://github.com/UNImoodle-gradereport_gradeconfigwizard.git"
  ["grade/export/checklist"]="https://github.com/davosmith/moodle-grade_checklist.git"
  ["grade/grading/form/rubric_ranges"]="https://github.com/catalyst/moodle-gradingform_rubric_ranges.git"
  ["availability/condition/role"]="https://github.com/moodle-an-hochschulen/moodle-availability_role.git"
  ["availability/condition/cohort"]="https://github.com/moodle-an-hochschulen/moodle-availability_cohort.git"
  ["availability/condition/xp"]="https://github.com/FMCorz/moodle-availability_xp.git"
  ["auth/saml2"]="https://github.com/catalyst/moodle-auth_saml2.git"
  ["auth/oidc"]="https://github.com/microsoft/moodle-auth_oidc.git"
  ["repository/office365"]="https://github.com/microsoft/moodle-repository_office365.git"
  ["repository/panopto"]="https://github.com/lucisgit/moodle-repository_panopto.git"
  ["local/o365"]="https://github.com/microsoft/moodle-local_o365.git"
  ["local/adminer"]="https://github.com/grabs/moodle-local_adminer.git"
  ["local/cohortrole"]="https://github.com/paulholden/moodle-local_cohortrole.git"
  ["local/course_merge"]="https://github.com/LafColITS/moodle-local_course_merge.git"
  ["local/categorybanner"]="https://github.com/Fanny1203/moodle-local_categorybanner.git"
  ["local/instructor_files"]="https://github.com/LafColITS/moodle-local_instructor_files.git"
  ["local/multiple_enrollments"]="https://github.com/E-learningTouch/moodle-local_multiple_enrollments.git"
  ["course/format/grid"]="https://github.com/gjbarnard/moodle-format_grid.git"
  ["course/format/topcoll"]="https://github.com/gjbarnard/moodle-format_topcoll.git"
  ["course/format/remuiformat"]="https://github.com/WisdmLabs/moodle-format_remuiformat.git"
  ["course/format/flexsections"]="https://github.com/marinaglancy/moodle-format_flexsections.git"
  ["course/format/tiles"]="https://bitbucket.org/dw8/moodle-format_tiles.git"
  ["admin/tool/hidecourses"]="https://github.com/LafColITS/moodle-tool_hidecourses.git"
  ["admin/tool/deletecourses"]="https://github.com/LafColITS/moodle-tool_deletecourses.git"
  ["admin/tool/mergeusers"]="https://github.com/jpahullo/moodle-tool_mergeusers.git"
  ["admin/tool/coursedates"]="https://github.com/LafColITS/moodle-tool_coursedates.git"
  ["admin/tool/editrolesbycap"]="https://github.com/moodleou/moodle-tool_editrolesbycap.git"
  ["admin/tool/supporter"]="https://github.com/eLearning-TUDarmstadt/moodle-tool_supporter.git"
  ["report/coursemanager"]="https://github.com/oliviervalentin/moodle-report_coursemanager.git"
  ["report/lmsace_reports"]="https://github.com/lmsace/moodle-report_lmsace_reports.git"
)

for path in "${!submodules[@]}"; do
  url="${submodules[$path]}"
  echo "Adding: git submodule add $url $path"
  git submodule add "$url" "$path"
done
